inherit: 
    - models/alignment-heads-6.yaml
    - wandb.yaml

model:
    n_dims: 5
    n_positions: 20

training:
    task: mixed_linear_alignment
    data: mixed_gaussian
    task_kwargs: {}
    batch_size: 256
    learning_rate: 0.0001
    save_every_steps: 500
    keep_every_steps: 100000
    train_steps: 3000
    curriculum:
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 2000
        points:
            start: 20
            end: 20
            inc: 3
            interval: 2000

out_dir: ../models/alignment-heads-6

wandb:
    name: "train_linear_alignment_toy"
